Bug: Not reaping containers that fail on build
- Containers that fail to build won't yet have an image.  Need to reap
those also

diff --git a/bin/stardock-reaper b/bin/stardock-reaper
--- a/bin/stardock-reaper
+++ b/bin/stardock-reaper
@@ -30,7 +30,7 @@ if [ -n "${SERVICE_DOCKER_TAG}" ]; then
       container=$(echo ${image_and_container} | cut -f2 -d',')
 
       if echo $id | egrep -q "^${image}"; then
-        
+
         info "reaper|kill_init_docker_image:${container}"
         ps auxw \
           | grep -v grep \
@@ -52,8 +52,104 @@ if [ -n "${SERVICE_DOCKER_TAG}" ]; then
   done
 fi
 
+function reap_containers() {
+  repository="$1"
+  name="$2"
+
+}
+
 
 # Reap any containers
+for image_and_name in $(docker container ls --format '{{.Image}},{{.Names}}' \
+    | grep --extended-regexp -e ",${order}-[a-f0-9]+-[a-f0-9]+" \
+    | grep --invert-match "${current_service_name}"); do
+
+  repository_and_tag="$(echo $image_and_name | cut -f1 -d',')"
+  repository="$(echo $repository_and_tag | cut -f1 -d':')"
+  tag="$(echo $repository_and_tag | cut -f2 -d':')"
+  name="$(echo $repository_and_tag | cut -f2 -d',')"
+
+  STATUS_FILE="${CURRENT_ORDERS}/${order}/.stardockstatus.${name}"
+  # If the status file exists get the status
+  [ -f "${STATUS_FILE}" ] && CURRENT_STATUS=$(cat "${STATUS_FILE}")
+  # Get the latest successful container deployment
+  CURRENT_CONTAINER=$(cat ${CURRENT_ORDERS}/${order}/.container)
+  # Determine where nginx is pointing
+  NGINX_CONTAINER=$(curl --connect-timeout 1 -s -XHEAD -i "http://localhost/${order}/" | grep -i "X-Stardock-Container" | cut -f 2 -d " " | tr -dc '[[:print:]]')
+
+  # *****************************
+  # Guards
+  # *****************************
+  # The following are a set of guards to prevent reaps from happening when we
+  # don't want them to happen
+
+  # Starphleet intentionally won't reap images that fail to build
+  # until a container for the same service successfully builds.  This mechanism
+  # intentionally leaves around failed images for debug purposes.  To facilitate
+  # this we check if the .container file (updates on success) is 'newer' than
+  # the status file of the container we are attempting to reap
+  if [ "${CURRENT_ORDERS}/${order}/.container" -ot "${STATUS_FILE}" ] &&
+  [ "${force}" != "true" ]; then
+    info "Unable to reap ${name} - Latest container ${CURRENT_CONTAINER} is not newer"
+    continue;
+  fi
+
+  # Only reap non-building images.  Being explicit about reap conditions
+  # so future statuses don't trigger accidental reapz
+  # We won't reap if all are true:
+  #   - The image is not online
+  #   - The image is not failed
+  #   - The image is not stopped
+  #   - The image is not failed to publish
+  #   - This server is a build only server ("build server" status)
+  if [ "${CURRENT_STATUS}" != "" ] &&
+  [ "${CURRENT_STATUS}" != "online" ] &&
+  [ "${CURRENT_STATUS}" != "stopped" ] &&
+  [ "${CURRENT_STATUS}" != "failed" ] &&
+  [ "${CURRENT_STATUS}" != "build server" ] &&
+  [ "${CURRENT_STATUS}" != "building failed" ] &&
+  [ "${CURRENT_STATUS}" != "publish failed" ] &&
+  [ "${force}" != "true" ]; then
+    info "Reaper: Unable to reap ${name} due to status: ${CURRENT_STATUS}"
+    continue;
+  fi
+
+  # We won't reap if any are true:
+  #   - The current active container is being attempted
+  #   - NGINX is pointing at this container
+  #   - Force is not enabled
+  if ([ "${CURRENT_CONTAINER}" == "${name}" ] ||
+  [ "${NGINX_CONTAINER}" == "${name}" ]) &&
+  [ "${CURRENT_STATUS}" != "build server" ] &&
+  [ "${force}" != "true" ]; then
+    info "Unable to reap ${name} - Active Container ${CURRENT_CONTAINER} - NGINX Pointing at ${NGINX_CONTAINER}"
+    continue;
+  fi
+
+  info "reaper|image:${name}"
+
+  info "reaper|kill_init:${name}"
+  ps auxw \
+    | grep -v grep \
+    | grep -v reaper \
+    | grep stardock-init-serve-order \
+    | grep "${name}" \
+    | awk '{print $2}' \
+    | xargs kill
+
+  info "reaper|destroy_container:${name}"
+  "${STARDOCK_BIN}/stardock-docker-container-destroy" "${name}"
+
+  info "reaper|purge_status:${name}"
+  rm "${CURRENT_ORDERS}/${order}/.stardockstatus.${name}"* || true
+
+  info "reaper|purge_logs:${name}"
+  rm "${STARDOCK_LOGS}/${name}.build.*"
+
+  info "reaper|complete:${name}"
+done
+
+# Reap any images
 for repository_and_tag in $(docker image ls --format '{{.Repository}},{{.Tag}}' \
     | grep --extended-regexp -e ",${order}-[a-f0-9]+-[a-f0-9]+" \
     | grep --invert-match "${current_service_name}"); do
@@ -63,7 +159,6 @@ for repository_and_tag in $(docker image ls --format '{{.Repository}},{{.Tag}}' 
   name="$(echo $repository_and_tag | cut -f2 -d',')"
 
   STATUS_FILE="${CURRENT_ORDERS}/${order}/.stardockstatus.${name}"
-
   # If the status file exists get the status
   [ -f "${STATUS_FILE}" ] && CURRENT_STATUS=$(cat "${STATUS_FILE}")
   # Get the latest successful container deployment
@@ -141,6 +236,7 @@ for repository_and_tag in $(docker image ls --format '{{.Repository}},{{.Tag}}' 
   rm "${STARDOCK_LOGS}/${name}.build.*"
 
   info "reaper|complete:${name}"
+
 done
 
 # After we destroy all containers above, technically, all status files would
